# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""Dummy workflow processor for stress testing.

Workflows generated by ``generate.py`` / ``cse_workflow.py`` carry no
shell command — only ``sleep_s`` and (optionally) ``fail_threshold``
kwargs. ``WorkflowShellCommandProcessor`` would fork a subprocess per
task to run the command, which dominates the per-task overhead at
sub-second granularities. When you want to measure pure
coordinator + queue + persistence throughput, this processor skips
the fork: it inherits ``WorkflowShellCommandProcessor`` for all the
completion-publish, cancel-poll, and queue-handle plumbing, but
overrides ``__call__`` to just ``asyncio.sleep`` and publish a
completion.

Launch a worker with::

    PYTHONPATH=examples/stress_test \\
    ai4s-jobq <account>/stress-test worker \\
        --proc dummy_processor.DummyWorkflowProcessor \\
        -n 20 \\
        --idle-timeout 5m \\
        --max-idle-backoff 2s

Make sure ``JOBQ_WORKFLOW_PREFIX=<account>/<prefix>`` is exported in every
worker shell — the parent ``WorkflowShellCommandProcessor`` reads it
to discover the completion queue and (optionally) the persistence
layer for cancel polls.

Failure model
-------------
Tasks may carry a ``fail_threshold`` kwarg (integer 0-100, set by the
workflow generator).  A task **always** fails when::

    sha256(task_name)[:2] % 100 < fail_threshold

Because the decision is a pure function of the task name, the failure
pattern is fully deterministic and reproducible.  Retries will also
fail, so the task is permanently failed and its downstream tasks will
be marked ``upstream_failed``.
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
from typing import Any

from ai4s.jobq.workflow.entities import WorkflowCompletion, serialize_output
from ai4s.jobq.workflow.worker import WorkflowShellCommandProcessor

LOG = logging.getLogger("ai4s.jobq.workflow.stress")


def _deterministic_fail(task_name: str, fail_threshold: int) -> bool:
    """Return True if *task_name* should fail on its first attempt.

    Takes the first two bytes of SHA-256(task_name) as a 16-bit value
    and checks ``value % 100 < fail_threshold``.  Two bytes give
    65,536 uniformly-distributed values, so the actual failure rate
    deviates from *fail_threshold* % by at most 0.01 percentage points.
    """
    if fail_threshold <= 0:
        return False
    digest = hashlib.sha256(task_name.encode()).digest()
    v = int.from_bytes(digest[:2], "big")
    return v % 100 < fail_threshold


class DummyWorkflowProcessor(WorkflowShellCommandProcessor):
    """In-process workflow task simulator with completion-queue emit.

    Reads ``sleep_s`` and ``fail_threshold`` from task kwargs,
    ``await asyncio.sleep(sleep_s)``, then publishes a
    :class:`~ai4s.jobq.workflow.entities.WorkflowCompletion` to the
    prefix-scoped completion queue via the inherited
    ``_publish_completion``. No subprocess fork, no output file —
    designed for stress runs where the test should not be dominated
    by per-task subprocess overhead.

    Deterministic failures: if ``fail_threshold`` is set in kwargs, the
    task **always** fails (every attempt) when
    ``sha256(task_name)[:2] % 100 < fail_threshold``.  See
    :func:`_deterministic_fail`.
    """

    _send_count: int = 0

    async def __call__(
        self,
        cmd: str = "",
        _job_id: str = "",
        bg_dirsync_to: str | None = None,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        _log_dimensions: dict[str, str] | None = None,
        **kwargs: Any,
    ) -> int:
        workflow_id = kwargs.pop("__workflow_id", None)
        task_name = kwargs.pop("__workflow_task", None)
        # Accept legacy synonym
        if not task_name:
            task_name = kwargs.pop("__task_name", None)
        attempt_no = kwargs.pop("__attempt_no", None)
        kwargs.pop("__upstream_output_refs", None)

        if not (workflow_id and task_name):
            raise RuntimeError(
                "DummyWorkflowProcessor only handles workflow tasks "
                "(missing __workflow_id / __workflow_task)"
            )

        sleep_s = float(kwargs.get("sleep_s", 0.1))
        fail_threshold = int(kwargs.get("fail_threshold", 0))
        if sleep_s > 0:
            await asyncio.sleep(sleep_s)

        # Deterministic failure: every attempt fails for selected tasks.
        success = not _deterministic_fail(task_name, fail_threshold)
        error = None if success else f"deterministic failure (threshold={fail_threshold}%)"
        output_ref = serialize_output({"task": task_name, "ok": True}) if success else None

        completion = WorkflowCompletion(
            workflow_id=workflow_id,
            task_name=task_name,
            success=success,
            output_ref=output_ref,
            error=error,
            attempt_no=attempt_no,
        )
        await self._publish_completion(completion)

        self._send_count += 1
        if self._send_count <= 3:
            LOG.info(
                "Dummy completion #%d: %s/%s success=%s",
                self._send_count,
                workflow_id,
                task_name,
                success,
            )
        return 0
